sudo: required
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "pypy"
before_install:
  - scripts/install-on-travis.sh
install:
  - pip install --requirement=requirements-travis.txt
  - LC_ALL=C pip install .
script:
  - make check
  - make full-coverage
after_success:
  - coveralls
branches:
  except:
    - /^[0-9]/
